//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWebAbel
{
    using System;
    using System.Collections.Generic;
    
    public partial class visita
    {
        public int visitaId { get; set; }
        public Nullable<int> contacto_id { get; set; }
        public string motivo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora_entrada { get; set; }
        public Nullable<System.TimeSpan> Hora_salida { get; set; }
        public string Nombre_completo { get; set; }
    
        public virtual contactos contactos { get; set; }
    }
}
